#! /bin/bash
#
# These commands are copied from the Arduino IDE output on my machine, and
# therefore have tons of absolute paths specific to my machine.
/Applications/Arduino.app/Contents/Java/arduino-builder -dump-prefs -logger=machine -hardware /Applications/Arduino.app/Contents/Java/hardware -hardware /Users/mfurtak/Library/Arduino15/packages -tools /Applications/Arduino.app/Contents/Java/tools-builder -tools /Applications/Arduino.app/Contents/Java/hardware/tools/avr -tools /Users/mfurtak/Library/Arduino15/packages -built-in-libraries /Applications/Arduino.app/Contents/Java/libraries -libraries /Users/mfurtak/Documents/Arduino/libraries -fqbn=arduino:avr:uno -ide-version=10805 -build-path /var/folders/np/xhp7x1l91_36sqsr6rkf5_180000gn/T/arduino_build_433865 -warnings=none -build-cache /var/folders/np/xhp7x1l91_36sqsr6rkf5_180000gn/T/arduino_cache_393308 -prefs=build.warn_data_percentage=75 -prefs=runtime.tools.arduinoOTA.path=/Applications/Arduino.app/Contents/Java/hardware/tools/avr -prefs=runtime.tools.avr-gcc.path=/Applications/Arduino.app/Contents/Java/hardware/tools/avr -prefs=runtime.tools.avrdude.path=/Applications/Arduino.app/Contents/Java/hardware/tools/avr -verbose /Users/mfurtak/Documents/Arduino/dungeon_crawl/dungeon_crawl.ino

/Applications/Arduino.app/Contents/Java/arduino-builder -compile -logger=machine -hardware /Applications/Arduino.app/Contents/Java/hardware -hardware /Users/mfurtak/Library/Arduino15/packages -tools /Applications/Arduino.app/Contents/Java/tools-builder -tools /Applications/Arduino.app/Contents/Java/hardware/tools/avr -tools /Users/mfurtak/Library/Arduino15/packages -built-in-libraries /Applications/Arduino.app/Contents/Java/libraries -libraries /Users/mfurtak/Documents/Arduino/libraries -fqbn=arduino:avr:uno -ide-version=10805 -build-path /var/folders/np/xhp7x1l91_36sqsr6rkf5_180000gn/T/arduino_build_433865 -warnings=none -build-cache /var/folders/np/xhp7x1l91_36sqsr6rkf5_180000gn/T/arduino_cache_393308 -prefs=build.warn_data_percentage=75 -prefs=runtime.tools.arduinoOTA.path=/Applications/Arduino.app/Contents/Java/hardware/tools/avr -prefs=runtime.tools.avr-gcc.path=/Applications/Arduino.app/Contents/Java/hardware/tools/avr -prefs=runtime.tools.avrdude.path=/Applications/Arduino.app/Contents/Java/hardware/tools/avr -verbose /Users/mfurtak/Documents/Arduino/dungeon_crawl/dungeon_crawl.ino

# Create an 8:3 compatible file name for the hex for use in the Simbuino online simulator
# http://simbuino4web.ppl-pilot.com/
cp /private/var/folders/np/xhp7x1l91_36sqsr6rkf5_180000gn/T/arduino_build_433865/dungeon_crawl.ino.hex /private/var/folders/np/xhp7x1l91_36sqsr6rkf5_180000gn/T/arduino_build_433865/DUNGEON.HEX
